.github/analyst_guide_getting_started.md, README.md
This branch makes some improvements on the package README and the Analyst Guide.
1. Removed duplication between the _Quick Start Guide_ on the README with the _Getting Started_ guide in the Analyst Guide.
1. Provided more detailed instructions on how to trigger a function documentation or view the underlying source code. 
1. Added link to guide users on how to use RStudio Projects as an alternative to `set_wd()`
1. Mention nuance of the use of forward slashes when providing file paths in R. 
1. Provide a link of queries back to the product documentation.
=> Documentation: improvements on README and Analyst Guide

R/create_line.R, R/identify_holidayweeks.R, man/identify_holidayweeks.Rd
This branch changes the default behaviour of some time series plots in the package to start their vertical axes from the origin. This is a simple fix by adding `+ ylim(0, NA)` to the end of the ggplot chains. 
Updated functions in this PR are:
1. `identify_holidayweeks()`
1. `create_line()` (effect ripples through to wrapper functions)
This fixes #42.
=> Feature: changes to time series plots to start axis from origin

R/flag_outlooktime.R, man/flag_outlooktime.Rd
This branch tackles the problem of `flag_outlooktime()` throwing up errors when a Standard Person Query is passed through. 
This is caused by outlook start and end times which are passed as `"7:30"` instead of `"07:30"`. This is overly strict and causes issues when using the `validation_report()`, which depends on `flag_outlooktime()`.
The solution is to add a formatter within the function which accepts both formats:
```R
if(any(grepl(pattern = "\\d{1}:\\d{1,2}", x = data$WorkingStartTimeSetInOutlook))){
data$WorkingStartTimeSetInOutlook <-
paste0("00", data$WorkingStartTimeSetInOutlook) %>%
substr(start = nchar(.) - 4, stop = nchar(.))
}
if(any(grepl(pattern = "\\d{1}:\\d{1,2}", x = data$WorkingEndTimeSetInOutlook))){
data$WorkingEndTimeSetInOutlook <-
paste0("00", …
```
=> Bug Fix: `flag_outlooktime()` throwing up error on Standard Person Queries

R/import_wpa.R, man/import_wpa.Rd
This branch added the ability to specify encoding for `import_wpa()`. The new default used is 'UTF-8'.
1. Added a new argument `encoding` in `import_wpa()`. This feature feeds onto the underlying `data.table::fread()` function. The default is changed to 'UTF-8' to work with double-byte characters.
This has been tested with some dummy data and works:
This fixes #73.
=> Bug Fix: reading double-byte characters in `import_wpa()`

R/collaboration_line.R
This branch fixes the error mentioned in #71 where `collab_line()` returns no output.
1. Fixed error within `collab_line()`. This does not affect other `*_line()` functions.
This fixes #71.
=> Bug fix: no return for `collab_line()`

R/collaboration_area.R, man/collaboration_area.Rd
This branch fixes the problem where the variable name checks in `collaboration_area()` is overly strict, and resolves it by making it case-sensitive. This branch is a direct fix of issue #72 as raised by @juliajuju93.
1. Makes the variable name checks within `collaboration_area()` **case-insensitive**.
1. Makes it a default behaviour to return the output with `hrvar` set to `NULL`, and adds the ability for it to run it as a total view. This is an extension of #22 raised by @AinizeCidoncha.
1. Expanded examples in the documentation of this function.  
This fixes #72.
=> Bugfix: relax variable name checks to `collab_area()` 

R/network_g2g.R, man/network_g2g.Rd
This branch makes some improvements to `network_g2g()`, including adding the ability to return an interactive matrix (#82) and providing a warning if `'Collaborators Within Group'` is missing from the values of the Collaborators column (#70).
1. Issue a warning signal if `Collaborators Within Group` is missing from the data.
1. When `"data"` is  passed to `return`, a long table of the underlying data is returned. When `"table"` is passed to `return`, an interaction matrix (as a data frame) is returned.
This fixes #70 and #82.
=> Feature: improvements to `network_g2g()`

R/mgrrel_matrix.R, man/mgrrel_matrix.Rd
This branch makes an improvement to `mgrrel_matrix()` as per #83, adding an ability to return a raw data view with `mgrrel_matrix()` where the coaching types can be joined back to a Standard Person Query for further analysis. Documentation is also improved.
1. When `"data"` is passed to `return`, a person-level data frame is returned. This can then be merged with any Person Query with the `PersonId` for further analysis.
1. Clean and refine documentation on argument types.
1. Additional examples added to the documentation. 
This fixes #83.
Coaching personas baseline visualized with `keymetrics_scan()`.
=> Feature: return typed data for `mgrrel_matrix()`

R/check_query.R, R/collaboration_report.R, R/create_rank.R
This branch updates the collaboration report with new visuals that are more relevant to the user. 
1. New version of the collaboration report
2. Changed a title in the `create_rank()` function for clarity
=> Feature: update plot visuals in  `collaboration_report()`

R/one2one_freq.R
This branch fixes an issue with `one2one_freq()`.
1. Fixes an issue with `one2one_freq()`
The solution appears to be that in `create_dist()`, which is called from `one2one_freq()`, previously defaulted to the `dist_colours` argument having a length of 4. In fact,  5 is needed, which was causing the previous error.
=> Bugfix: update `one2one_freq()`

R/init.R, R/workpatterns_classify.R, R/workpatterns_classify_bw.R, man/workpatterns_classify.Rd
This branch makes improvement to some outputs of working patterns functions. 
1. Made possible for the `"data"` return option for `workpatterns_classify_bw()` to return HR attributes. (#129)
1. Removed the confusing `Signals.Total.x` and `Signals.Total.y` which is resulted from a duplicate column when performing a joining between datasets for `workpatterns_classify_bw()`. 
1. Added documentation of definitions for working patterns. (#124)
1. Removed package version number from start-up message to avoid inconsistency. 
This fixes #124 and #129.
=> Feature: improve return outputs of working patterns functions

NEWS.md, R/create_IV.R, man/create_IV.Rd
This branch improves error handling on IV functions, especially in relation to predictors in which their p-values fall below the required significance level set at `siglevel`. A new argument `exc_sig` has been added. 
1. Added argument `exc_sig` to `create_IV()`
2. Added error message if no predictors are left after predictors have been filtered out.
=> Feature: improve error handling on IV functions

NEWS.md, R/create_bar_asis.R, R/flex_index.R, R/identify_shifts_wp.R, R/workpatterns_classify.R, R/workpatterns_classify_bw.R, man/flex_index.Rd, man/identify_shifts_wp.Rd, man/workpatterns_classify.Rd, man/workpatterns_classify_bw.Rd
This branch addresses some feature and documentation requests for both `workpatterns_classify()` and `flex_index()`. 
1. Reintroduce old visual of heatmap distribution of activity across hours of the day (#143).
2. Replaced colours of heatmap distribution visual from red to `#1d627e` (#143)
3. Update wording to reflect the recurring nature of breaks (#158)
4. Added ability to run percentages for `identify_shifts_wp()` (#155)
This fixes #143, #155, #158.
=> Feature: improvements to working patterns and flexibility index

_pkgdown.yml
This pull request updates `_pkgdown.yml` to implement the Doc Search function. Instructions as per <https://pkgdown.r-lib.org/articles/search.html>.
This branch is merged with `cran-mirror` rather than `main` to immediately deploy the search function (`main` is not deployed until the latest version of the package is submitted and accepted to CRAN).
=> Feature: implement Doc Search

DESCRIPTION, NEWS.md, R/flex_index.R, R/plot_flex_index.R, R/workpatterns_classify_bw.R, man/flex_index.Rd
This branch add meetings and unscheduled call signals for `flex_index()`, as per #183. Some visual improvements are also made to top work pattern plots. 
1. Add meetings and unscheduled call signals for `flex_index()`.
2. Bring colour formatting in the work patterns plots in `flex_index()` in line with `workpatterns_classify()`. The underlying code is edited at `plot_flex_index()` (see `workpatterns_classify_bw()`)
3. Increment to development version `1.6.1.9000`
This fixes #183.
=> Feature: add meetings and unscheduled call signals for `flex_index()`

NEWS.md, R/validation_report.R, man/validation_report.Rd
Some person flexible queries no longer provide `Call_hours` by default. This branch implements a feature change that makes the use of the variable dynamic and prevents it from returning an error if missing.
1. Make the use of `Call_hours` variable dynamic in `validation_report()`
2. Update documentation in `validation_report()` and `NEWS.md` accordingly. 
3. Prepare release of `v1.6.2`.
=> Feature: make use of `Call_hours` dynamic in `validation_report()`

R/workpatterns_area.R, R/workpatterns_classify_pav.R, R/workpatterns_hclust.R
We are updating `tidyr::replace_na()` to utilize the vctrs package, and that results in slightly stricter / more correct type conversions. See https://github.com/tidyverse/tidyr/pull/1219
We noticed in revdeps that this package broke. An easy way to see this is by installing the above mentioned PR and running:
``` r
library(wpa)
orgs <- c("Customer Service", "Financial Planning", "Biz Dev")
em_data <- em_data[em_data$Organization %in% orgs, ]
workpatterns_area(em_data, return = "plot", values = "percent")
#> Error: Problem with `mutate()` column `PersonId`.
#> ℹ `PersonId = (structure(function (..., .x = ..1, .y = ..2, . = ..1) ...`.
#> x Can't convert `replace` <double> to match type of `data` <character>.
```
The problem boils down to the fact that you are calling `mutate_all(df, …
=> Fix: only call `replace_na(., 0)` on numeric columns

R/workpatterns_classify_bw.R
We are planning on releasing tidyr 1.2.0 towards the end of this month.
We noticed in revdeps that this package was broken. An easy way to reproduce is to install the dev version of tidyr and run this code:
``` r
library(wpa)
em_data %>% 
workpatterns_classify(method = "bw", return = "plot-area")
#> Error: Problem with `summarise()` input `..1`.
#> ℹ `..1 = complete(data = dplyr::cur_data(), ..., fill = fill, explicit = explicit)`.
#> x object 'Date' not found
#> ℹ The error occurred in group 1: Date = 2020-01-05.
```
The problem comes down to the fact that you are trying to `complete()` on a grouping variable, `Date`. In the development version, `complete()` has been fixed to actually work correctly with grouped data frames in all cases (see https://github.com/tidyverse/tidyr/issues/396 …
=> Ungroup before completing

R/network_p2p.R, man/network_leiden.Rd, man/network_p2p.Rd
This branch fixes a bug reported in #221 where the Louvain implementation in `network_p2p()` cannot be made deterministic. 
1. Expands the ability to set seed within the function environment with the `seed` argument in `network_p2p()` to when `display = "louvain"` (previously only affects `display = "leiden"`). 
2. Update relevant documentation. 
This fix is confirmed to be working with:
```R
library(wpa)
p2p_data <- p2p_data_sim()
a <- 
p2p_data %>%
network_p2p(
display = "louvain",
return = "table",
seed = 100
)
b <- 
p2p_data %>%
network_p2p(
display = "louvain",
return = "table",
seed = 100
)
nrow(a) == nrow(b)
all(a$cluster == b$cluster)
```
This fixes #221.
=> Bugfix: make Louvain implementation in `network_p2p()` deterministic (#221)

.github/workflows/R-CMD-check.yaml, CRAN-SUBMISSION, DESCRIPTION, NEWS.md, R/workpatterns_classify_bw.R, README.md, cran-comments.md
Hi there,
We ran revdeps for the upcoming release of tidyr 1.3.0 and your package came up.
In dev tidyr we have reworked the way that data frame "restoration" is done in a number of the tidyr verbs to be simpler, more robust, and resolve a number of edge case issues. Unfortunately for wpa, this means that the data.table class is no longer preserved in a place where it was expected to be. I've fixed that with an explicit `as.data.table()` call.
We actually plan to release tidyr today. I'm not sure how wpa slipped through the cracks when we ran revdeps a few weeks ago. I'm sorry about that!
This patch is backwards compatible with CRAN tidyr.
Thanks!
=> Eagerly convert from and to data.table and patch `v1.8.1`
